name: NodeJS-project-test-build-Deploy
on: push
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Downloading Code-step-1
        uses: actions/checkout@v3
      - name: Install NodeJS-step-2
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies-step-3
        run: npm ci
      - name: npm test-setep-4
        run: npm test
  Building:
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: Downloading Code-step-1
        uses: actions/checkout@v3
      - name: Install NodeJS-step-2
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies-step-3
        run: npm ci
      - name: build project-step-4
        run: npm run build
  Deploying:
    needs: Building
	runs-on: ubuntu-latest
	steps:
	  - name: Deploying
	    run: echo Deploying
	

